resources:
  sentry:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      cpu: "50m"
      memory: "128Mi"
  web:
    requests:
      cpu: "20m"
      memory: "96Mi"
    limits:
      cpu: "100m"
      memory: "192Mi"
image:
  repository: ahmedbodi/bitaxe-sentry
  tag: v0.4.1
  pullPolicy: Always
env:
  DB_URL: sqlite:///data/bitaxe.db
  POLL_INTERVAL_MINUTES: 15
  RETENTION_DAYS: 30
  TEMP_MIN: 20
  TEMP_MAX: 70
  VOLT_MIN: 5.0
  BITAXE_ENDPOINTS: ""
  DISCORD_WEBHOOK_URL: ""
persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
ingress:
  url: bitaxe.it4f.co.uk
  http:
    enabled: true
    annotations: |
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: web
      traefik.ingress.kubernetes.io/router.middlewares: kube-system-redirect-to-https@kubernetescrd
      external-dns.alpha.kubernetes.io/internal: "true"
      external-dns.alpha.kubernetes.io/external: "true"
  https:
    enabled: true
    annotations: |-
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
      external-dns.alpha.kubernetes.io/internal: "true"
      external-dns.alpha.kubernetes.io/external: "true"
